### ISSUE TITLE
Rebase or merge

### ISSUE THREAD

**Issue by nolde** [saitho/semantic-release-backmerge#10]
Hello @saitho !

After resolving the issue in #8 , I ran into another problem.

Your `backmerge` wants to rebase `develop` over `master`. That might not be a problem for most users, but in my case it is not possible due to repository constraints; to avoid the risk of having people overwriting `develop` by mistake, we block history rewrite of both `master` and `develop`.

Would it be possible to choose whether to rebase or merge? I usually manually merge, and it works just as well as rebasing (it does set the tag history right), although generating a less pleasant commit tree/graph. Would it be possible to add a setting for that?

**Comment by saitho** [comment]
Sure, will do that. :)

**Comment by saitho** [comment]
A new setting `backmergeStrategy` is available with the latest release v1.4.0.
Set it to "merge" and it will merge _master_ into _develop_.

**Comment by nolde** [comment]
Thanks a lot @saitho , I really appreciate the support!

Your tool is a godsend! Thanks again!

**Comment by saitho** [comment]
You're welcome. Feel free to star the repository, if you like it. :)
