### ISSUE TITLE
Unknown option for merge-recursive: -X ours

### ISSUE THREAD

**Issue by nolde** [saitho/semantic-release-backmerge#23]
Getting the following error when using "ours" strategy, using `@saithodev/semantic-release-backmerge@1.5.0`:
```
[8:00:40 AM] [semantic-release] › ✖  An error occurred while running semantic-release: Error: Command failed with exit code 128: git merge -X ours origin/master
fatal: Unknown option for merge-recursive: -X ours
```

Config:
```
          [
            '@saithodev/semantic-release-backmerge',
            {
              clearWorkspace: true,
              backmergeStrategy: 'merge',
              mergeMode: 'ours',
              plugins: [['@semantic-release/exec', { successCmd: backmergeSuccess }]]
            }
          ]
```

I think the correct way to use it is `-Xours`, without space character. A few examples where it shows up like that:

- https://bigfont.ca/git-rebase-strategy-with-xours/
- https://git-scm.com/docs/git-merge#Documentation/git-merge.txt-ours
- https://demisx.github.io/git/rebase/2015/07/02/git-rebase-keep-my-branch-changes.html

**Comment by saitho** [comment]
Looks like it. Wasn't really apparent from looking at the Git documentation (didn't look too closely at the examples)
