### ISSUE TITLE
bug: Protected branch update failed

### ISSUE THREAD

**Issue by EinfachHans** [saitho/semantic-release-backmerge#27]
## Current behavior

we got the following error in a project: `remote: error: GH006: Protected branch update failed for refs/heads/dev.`
This is, because we have a rule that we need a PR which has at least one approved review. But Admins can push to the repo without it.

In the action that starts semantic release we set a `GITHUB_TOKEN` env from an account that has admin rights but this seems not to work.

## Expected behavior

Maybe the `GITHUB_TOKEN` isn't used?

## Environment

- **semantic-release/semantic-release** version: 17.4.7
- CI environment: GitHub Action
- **@saithodev/semantic-release-backmerge** version: 1.5.3

**Comment by saitho** [comment]
Hacktoberfest is happening right now: https://hacktoberfest.digitalocean.com/
I've just added the tag to this repo, maybe someone comes around to investigate this. ;)
