### ISSUE TITLE
Should perform backmerge even when no new version is released?

### ISSUE THREAD

**Issue by DiogoAbu** [saitho/semantic-release-backmerge#37]
As of right now the backmerge is perfomed only when a release is published.
This means that if we make a commit that are not associated with `patch`, `minor` or `major` releases, it will not be backmerged.

But it should?

In any case, there's no `semantic-release` hook for when a release is not published, but there is a [PR](https://github.com/semantic-release/semantic-release/issues/1712).

**Comment by saitho** [comment]
As this is only a plugin to `semantic-release`, we can only interact with the hooks provided by `semantic-release`.
Once the PR is merged, this feature could be added as well.
For now, backmerge only happens after a release succeeded.
