### ISSUE TITLE
Broken example of plugins

### ISSUE THREAD

**Issue by aleksandar-babic** [saitho/semantic-release-backmerge#4]
Hi,

Looks like the example of how to use `plugins` (with `exec` plugin) is broken.

When the config is set to what example suggests :

```json
{
  "plugins": [
    "@semantic-release/commit-analyzer",
    "@semantic-release/release-notes-generator",
    ["@saithodev/semantic-release-backmerge", {
      "branchName": "dev",
      "plugins": ["@semantic-release/exec", {
        "successCmd": "echo 'Version in master is ${nextRelease.version}' > test.txt && git add test.txt"
      }]
    }]
  ]
}
```

This error happens `Invalid plugin provided. Expected string or array, got object`.

This happens due to L34 in `plugins.ts` where for of loop iterates through the plugins array (2 iterations, first `"@semantic-release/exec"`, second `{"successCmd": "echo 'Version in master is ${nextRelease.version}' > test.txt && git add test.txt" }`).
https://github.com/saitho/semantic-release-backmerge/blob/51346a4a59198137dd2edfdf08e953f7937f97c5/src/helpers/plugins.ts#L34
Error is triggered on second iteration as that gets Object instead of expected array/string.

Workaround to fix this is to wrap value of `plugins` in another(nested) array, something like this:
```json
{
  "plugins": [
    "@semantic-release/commit-analyzer",
    "@semantic-release/release-notes-generator",
    "@saithodev/semantic-release-backmerge",
    {
      "branchName": "dev",
      "plugins": [
        [
          "@semantic-release/exec",
          {
            "successCmd": "echo 'Version in master is ${nextRelease.version}' > test.txt && git add test.txt"
          }
        ]
      ]
    }
  ]
}
```

So either example, or implementation needs to be changed.

Let me know if you need more details 😄

**Comment by saitho** [comment]
Your're right. The inner plugin definition should follow the same structure as the plugin configuration used by semantic-release.
I adjusted the example in the README. Hope that works for you. :)

**Comment by aleksandar-babic** [comment]
@saitho  looks good!
