### ISSUE TITLE
Add lodash templating cap to branchName option

### ISSUE THREAD

**Issue by AlbertoLopSie** [saitho/semantic-release-backmerge#5]
That would allow to backmerge to any other branch besides `develop` 

I'd like to backmerge to any branch the merge come from using the lodash template `$(branch.name}`  for example (as used in the `message` option)

Thanks!

**Comment by saitho** [comment]
Hi there,

sorry for the late reply. Sounds useful.
I'm not using this plugin myself anymore as I abandoned using develop branches.
I've added templating for the branchName option, please try it out. ;)

**Comment by saitho** [comment]
Released in version **1.2.0**
