### ISSUE TITLE
You have unstaged changes when backmerging

### ISSUE THREAD

**Issue by nolde** [saitho/semantic-release-backmerge#8]
I am getting this issue, and I am guessing it is due to changelog and/or dist files, but I am not quite sure if this is it.

```
[5:08:52 AM] [semantic-release] › ✔  Completed step "success" of plugin "@semantic-release/exec"
[5:08:52 AM] [semantic-release] › ℹ  Start step "success" of plugin "@saithodev/semantic-release-backmerge"
[5:08:52 AM] [semantic-release] [@saithodev/semantic-release-backmerge] › ℹ  Release succeeded. Performing back-merge into branch "develop".
[5:08:53 AM] [semantic-release] › ✖  Failed step "success" of plugin "@saithodev/semantic-release-backmerge"
[5:08:53 AM] [semantic-release] › ✖  An error occurred while running semantic-release: Error: Command failed with exit code 1: git rebase origin/master
error: cannot rebase: You have unstaged changes.
error: Please commit or stash them.
```

Config below:

``` 
const changelogFile = 'CHANGELOG.md'
const writerOpts = { commitsSort: ['subject', 'scope'] }
const prepareCmd = `npm run build:${STAGE}`
const release = 'sh .release.sh ${nextRelease.version}'
const preset = 'conventionalcommits'
const backmerge = 'npm --no-git-tag-version version "${nextRelease.version}-dev" && git add -u'

// ...

          ['@semantic-release/commit-analyzer', { preset }],
          ['@semantic-release/npm', { npmPublish: false }],
          ['@semantic-release/release-notes-generator', { preset, presetConfig, writerOpts }],
          ['@semantic-release/changelog', { changelogFile }],
          ['@semantic-release/exec', { prepareCmd, successCmd: release }],
          ['@semantic-release/git'],
          [
            '@saithodev/semantic-release-backmerge',
            {
              plugins: [['@semantic-release/exec', { successCmd: backmerge }]]
            }
          ]
        ]
```

Any ideas on what am I doing wrong?

**Comment by saitho** [comment]
Hi @nolde,

The rebase happens before your backmerge command (`successCmd`) is executed.
There seem to be uncommitted changes after your regular release finished.

For now try to remove those files or stash them away using `git stash` before executing `npm version`.
Can you try that?

I'll consider adding a setting to stash away changes before rebasing.

**Comment by nolde** [comment]
So, I should be able to use `verifyConditions` in `@semantic-release/exec` that's inside `@saithodev/semantic-release-backmerge` to stash, and then use `done` to pop the stash (I may some of those files in the next step of my CI pipeline) ?

**Comment by saitho** [comment]
The `success` step is actually triggered after the files were rebased and before the added files are pushed.
My suggestion I mentioned above won't work then, as that's too late.

I'll add two new settings `clearWorkspace` and `restoreWorkspace`:

* `clearWorkspace` will stash all uncommitted files before the rebase happens.
* `restoreWorkspace` will restore the stashed files after the backmerge was pushed.

Will that work for your use case?

**Comment by nolde** [comment]
That makes sense, and would probably work in my case. Stashing should be enough to stop git from complaining!

I will test a few options with `exec` inside and outside of `backmerge` to find a combination that works as well, I'll let you know how it goes.

Thanks for the support, mate!

**Comment by saitho** [comment]
Hi @nolde,

I've just pushed the implementation to the branch `feature/8-stash_workspace` (#9).
While the unit tests are fine, I need some more time to test this properly to see if the approach actually works.

Feel free to also try it yourself – but you'll have to compile the TypeScript yourself when checking out the branch, as the JavaScript dist is not part of the repository.

**Comment by nolde** [comment]
Hi @saitho !

Your change worked like a charm: it was able to stash and continue! Thank you!

I did run into another problem, but I will open another issue for it, as it is unrelated.
